[ForceLevelNotifier.Logger]
; Enables INFO-level logging (recommended)
bEnableInfo	 = true

; Enables DEBUG-level logging (developer-focused)
bEnableDebug = true

; Enables TRACE-level logging (very verbose)
bEnableTrace = true