[ForceLevelNotifier.AlertWatcherActor]
; Polling Rate in Geoscape for Force Level changes, in seconds.
; Lowering this value shortens the average time between the increase in Force Level and the notification (or scanning pause) from this mod.
; However setting this value too low might decrease FPS in Geoscape.
;
; For me there was zero difference in FPS in Geoscape without this mod and with this mod having fPollingRate = 0.1
; If you experience low FPS in Geoscape - you might want to increase this value.
; Lowest value is 0.1 sec - lower values will be forced to 0.1
fPollingRate = 0.1